"""Topic catalog — lightweight knowledge base discovery signal.

Scans the knowledge base at heartbeat time to build a compact map of what topics
and projects exist. Injected into every session context so the agent knows what
it can search without having to guess.

Generated by: heartbeat route_topic_catalog()
Consumed by:  build_session_context() → <memory-tools> block
"""

import json
import re
from collections import Counter
from pathlib import Path
from typing import Optional

_STOPWORDS = frozenset({
    # Articles, conjunctions, prepositions
    "the", "and", "for", "with", "from", "that", "this", "into", "about",
    "than", "then", "them", "their", "there", "which", "these", "those",
    "through", "without", "where", "when", "what", "also", "each",
    # Generic verbs
    "have", "will", "been", "were", "able", "after", "using", "should",
    "would", "could", "does", "dont", "must", "make", "made", "need",
    "requires", "require", "returns", "return", "allows", "enable", "enables",
    "working", "works", "adding", "added", "support", "update", "updated",
    "based", "fixed", "fixes", "removed", "removing", "setting", "sets",
    "running", "used", "uses", "uses", "apply", "applied", "changes",
    # Filler
    "now", "all", "one", "two", "three", "how", "but", "out", "any",
    "can", "use", "set", "run", "add", "get", "new", "old", "via", "per",
    "yes", "just", "only", "both", "like", "most", "well", "back",
    "its", "may", "has", "was", "are", "not", "your", "they", "some",
    "more", "home", "local", "right", "left", "true", "false", "same",
    "mode", "flag", "type", "path", "file", "files", "note", "notes",
    "work", "task", "done", "step", "make", "call", "calls", "test",
    "data", "time", "version", "value", "error", "issue", "fixes",
})

_MIN_TERM_LEN = 4
_TOP_N = 25


def _slug_to_terms(slug: str) -> list[str]:
    """Convert a file stem slug to constituent terms.

    '2026-03-06-traefik-routing-gotcha' → ['traefik', 'routing', 'gotcha']
    """
    # Strip leading date prefix (YYYY-MM-DD-)
    clean = re.sub(r"^\d{4}-\d{2}-\d{2}-", "", slug)
    parts = re.split(r"[-_]+", clean)
    return [p.lower() for p in parts if len(p) >= _MIN_TERM_LEN and p.lower() not in _STOPWORDS]


def _extract_title_terms(text: str) -> list[str]:
    """Extract terms from the first # heading of a markdown file."""
    for line in text.splitlines():
        if line.startswith("# "):
            title = line[2:].strip()
            # Split on spaces and punctuation
            parts = re.split(r"[\s\-_/|:,.()\[\]]+", title)
            return [
                p.lower() for p in parts
                if len(p) >= _MIN_TERM_LEN and p.lower() not in _STOPWORDS
            ]
    return []


def build_topic_catalog(agent: Optional[str] = None) -> dict:
    """Build the topic catalog from the current knowledge base state.

    Returns a dict with:
      projects: list of project directory names
      top_topics: list of {term, count} dicts, sorted by count descending
      generated: ISO date string

    Never raises — returns empty catalog on any error.
    """
    from datetime import datetime
    from innie.core import paths

    try:
        data_dir = paths.data_dir(agent)
        term_counts: Counter = Counter()

        # Project names from data/projects/
        projects: list[str] = []
        projects_dir = paths.projects_dir(agent)
        if projects_dir.exists():
            projects = sorted(
                d.name for d in projects_dir.iterdir()
                if d.is_dir() and not d.name.startswith("_")
            )
            # Count each project name as a high-frequency term
            for proj in projects:
                for term in re.split(r"[-_]+", proj):
                    if len(term) >= _MIN_TERM_LEN and term.lower() not in _STOPWORDS:
                        term_counts[term.lower()] += 5  # weight project names higher

        # Learnings: terms from file stems + title headings
        learnings_dir = paths.learnings_dir(agent)
        if learnings_dir.exists():
            for f in learnings_dir.rglob("*.md"):
                if f.name.startswith("_"):
                    continue
                # Terms from slug
                for term in _slug_to_terms(f.stem):
                    term_counts[term] += 1
                # Terms from title heading
                try:
                    text = f.read_text(encoding="utf-8", errors="ignore")
                    # Skip frontmatter
                    if text.startswith("---"):
                        end = text.find("---", 3)
                        if end != -1:
                            text = text[end + 3:]
                    for term in _extract_title_terms(text):
                        term_counts[term] += 1
                except OSError:
                    pass

        # Top N terms (excluding project names already listed separately)
        project_set = {p.lower() for p in projects}
        top_topics = [
            {"term": term, "count": count}
            for term, count in term_counts.most_common(_TOP_N * 2)
            if term not in project_set
        ][:_TOP_N]

        return {
            "generated": datetime.now().strftime("%Y-%m-%d"),
            "projects": projects,
            "top_topics": top_topics,
        }

    except Exception:
        return {"generated": "", "projects": [], "top_topics": []}


def save_topic_catalog(catalog: dict, agent: Optional[str] = None) -> None:
    """Write catalog to state/topic-catalog.json."""
    from innie.core import paths

    out = paths.topic_catalog_file(agent)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(catalog, indent=2), encoding="utf-8")


def load_topic_catalog(agent: Optional[str] = None) -> dict | None:
    """Load catalog from state/topic-catalog.json. Returns None if not found."""
    from innie.core import paths

    f = paths.topic_catalog_file(agent)
    if not f.exists():
        return None
    try:
        return json.loads(f.read_text(encoding="utf-8"))
    except Exception:
        return None


def format_catalog_for_context(catalog: dict) -> str:
    """Format catalog as a compact injection string for <memory-tools>.

    Example output:
      Memory catalog: docker (31), traefik (14), vllm (7), harbor (9)
      Projects: innie-engine, polyjuiced, homelab-ai, bird
    """
    lines = []

    topics = catalog.get("top_topics", [])
    if topics:
        top = topics[:12]  # limit to 12 for compactness
        topic_str = ", ".join(f"{t['term']} ({t['count']})" for t in top)
        lines.append(f"Memory catalog: {topic_str}")

    projects = catalog.get("projects", [])
    if projects:
        lines.append(f"Projects: {', '.join(projects[:10])}")

    return "\n".join(lines)
